# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9573e618946d70a56701d2de18b74ba00c09ffa42af5ca455d878847619d1bdd44d0b1edf37e289697310d7c9525b730c8eccc4f9cd90327925107ba743ea88

test:
  secret_key_base: f1161ef4d656f566710e59cd6061bd92a374c5ae7ad8eff25620cda6db32c7297220abd1ea51c704f361d6be021143990b8cccf7126233f1e15507594a6b7e2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
